if(NOT DEFINED INPUT OR NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "Fish catalog input is missing: ${INPUT}")
endif()
if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "")
    message(FATAL_ERROR "Default price catalog output is required")
endif()

file(READ "${INPUT}" catalog_json)
string(JSON schema_version ERROR_VARIABLE schema_error GET "${catalog_json}" schemaVersion)
if(schema_error OR NOT schema_version EQUAL 1)
    message(FATAL_ERROR "Fish catalog schemaVersion must be 1: ${schema_error}")
endif()
string(JSON catalog_id ERROR_VARIABLE id_error GET "${catalog_json}" catalogId)
if(id_error OR NOT catalog_id STREQUAL "sonar-fishing-fish")
    message(FATAL_ERROR "Fish catalog id is invalid: ${id_error}")
endif()
string(JSON fish_count ERROR_VARIABLE count_error LENGTH "${catalog_json}" fishes)
if(count_error OR NOT fish_count EQUAL 31)
    message(FATAL_ERROR "Fish catalog must contain exactly 31 entries: ${count_error}")
endif()

set(output_text
    "#include \"sonar/fishing/session_statistics/session_statistics.h\"\n\nnamespace sonar::fishing::session_statistics {\n\nPriceCatalog DefaultPriceCatalog() {\n  return {\n"
)
set(price_count 0)
math(EXPR last_index "${fish_count} - 1")
foreach(index RANGE 0 ${last_index})
    string(JSON fish_id ERROR_VARIABLE fish_id_error GET "${catalog_json}" fishes ${index} id)
    if(fish_id_error OR NOT fish_id MATCHES "^[a-z0-9_]+$")
        message(FATAL_ERROR "Fish catalog id is invalid at entry ${index}")
    endif()

    string(JSON price_type ERROR_VARIABLE price_error TYPE "${catalog_json}" fishes ${index} price)
    if(price_error)
        continue()
    endif()
    if(NOT price_type STREQUAL "OBJECT")
        message(FATAL_ERROR "Fish catalog price must be an object at entry ${index}")
    endif()

    foreach(field IN ITEMS perItemMin perItemMax per1000Min per1000Max)
        string(JSON ${field} ERROR_VARIABLE field_error GET "${catalog_json}" fishes ${index} price ${field})
        if(field_error OR NOT ${field} MATCHES "^[0-9]+([.][0-9]+)?$")
            message(FATAL_ERROR "Fish catalog price ${field} is invalid at entry ${index}")
        endif()
    endforeach()
    if(perItemMin GREATER perItemMax OR per1000Min GREATER per1000Max)
        message(FATAL_ERROR "Fish catalog price range is invalid at entry ${index}")
    endif()

    string(APPEND output_text
        "      {\"${fish_id}\", FishPrice{${perItemMin}, ${perItemMax}, ${per1000Min}, ${per1000Max}}},\n"
    )
    math(EXPR price_count "${price_count} + 1")
endforeach()
if(NOT price_count EQUAL 20)
    message(FATAL_ERROR "Fish catalog must contain exactly 20 default prices")
endif()
string(APPEND output_text "  };\n}\n\n}  // namespace sonar::fishing::session_statistics\n")

get_filename_component(output_directory "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_directory}")
file(WRITE "${OUTPUT}" "${output_text}")
