if(NOT DEFINED INPUT OR NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "Fish catalog input is missing: ${INPUT}")
endif()
if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "")
    message(FATAL_ERROR "Fish catalog output is required")
endif()

file(READ "${INPUT}" catalog_json)
string(JSON schema_version ERROR_VARIABLE schema_error GET "${catalog_json}" schemaVersion)
if(schema_error OR NOT schema_version EQUAL 1)
    message(FATAL_ERROR "Fish catalog schemaVersion must be 1: ${schema_error}")
endif()
string(JSON catalog_id ERROR_VARIABLE id_error GET "${catalog_json}" catalogId)
if(id_error OR NOT catalog_id STREQUAL "sonar-fishing-fish")
    message(FATAL_ERROR "Fish catalog id is invalid: ${id_error}")
endif()
string(JSON fish_count ERROR_VARIABLE count_error LENGTH "${catalog_json}" fishes)
if(count_error OR NOT fish_count EQUAL 31)
    message(FATAL_ERROR "Fish catalog must contain exactly 31 entries: ${count_error}")
endif()

set(output_text "#pragma once\n\nconstexpr std::array<FishDefinition, ${fish_count}> kFishCatalog{{\n")
math(EXPR last_index "${fish_count} - 1")
foreach(index RANGE 0 ${last_index})
    string(JSON fish_id ERROR_VARIABLE fish_id_error GET "${catalog_json}" fishes ${index} id)
    string(JSON display_name ERROR_VARIABLE display_error GET "${catalog_json}" fishes ${index} displayName)
    if(fish_id_error OR display_error)
        message(FATAL_ERROR "Fish catalog entry ${index} is invalid")
    endif()
    if(NOT fish_id MATCHES "^[a-z0-9_]+$")
        message(FATAL_ERROR "Fish catalog id is invalid: ${fish_id}")
    endif()
    string(REPLACE "\\" "\\\\" display_name "${display_name}")
    string(REPLACE "\"" "\\\"" display_name "${display_name}")
    string(APPEND output_text "    {\"${fish_id}\", \"${display_name}\"},\n")
endforeach()
string(APPEND output_text "}};\n")

get_filename_component(output_directory "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_directory}")
file(WRITE "${OUTPUT}" "${output_text}")
